### ISSUE TITLE
Add custom CSS options (desktop and mobile)

### ISSUE THREAD

**Issue by insin** [insin/hn-comments-owl#22]
Add options to provide custom CSS via a `<textarea>` in extension options and on your profile page

e.g. for more comfortable comment reading on desktop

```css
#hnmain { max-width: 72ch; }
.comment{ line-height: 1.5rem; font-size: .875rem; padding-right: 1rem; }
.default p { margin-top: 1rem; }
```
